### ISSUE TITLE
API Consistency & Improvements

### ISSUE THREAD

**Issue by ryanartecona** [docopt/docopt.hs#10]
When writing the current version of the public API, I loosely aimed to make it easy enough for myself to use it. I was still pretty new to Haskell at the time. I have a better idea of how it should work now. 

There are currently several variants of `optionsWithUsage` in play, with more on the way from #7. 

  1. with/without `Debug`: these have the same type signature but *very* different behavior, since the `Debug` variants print whatever `ParseError` they encounter (either from parsing the usage or the arguments, though it's left ambiguous) before exiting, if an error is encountered.
  2. with/without `File`: these are...special. Not only do they differ in that they take a `FilePath` instead of a string, they also implicitly call `getArgs` internally instead of expecting `[String]` from the caller. **Worse**, they open the file at runtime relative to the user's $PWD, which makes their existence misleading at best and harmful at worst.
  3. **new from #7** quasiquoters `docopt` and `docoptFile`: these force a separation between a `ParseError` from the usage page at *compile time* from one due to a bad program invocation at *runtime*. The `File` version here also *does not* depend on the $PWD at runtime.
  4. monadic argument query functions: there are `...M` versions of some, but not all, of the argument query functions. The intent of these was *purely* to allow the direct use of `<-` from within a `do` block. Since they also lack much documentation, their existence might (wrongfully) imply they behave differently from the non-monadic versions (they don't, they just `return`).

#### My thoughts:

  1. [x] For the with/without `Debug` variants, 
    1. there are old changes in the friendly-api branch that switch these to use a single function with a config record, which should be merged
    2. it would be nice to have the debug variant return an `IO (Either ParseError Arguments)` instead of printing the parse error and exiting. That should probably be added.
  2. [x] Going forward, encourage the quasiquoters as the primary entry points for the library. They are the friendliest, and they don't do any unnecessary parsing at runtime to boot.
  3. [x] Get rid of the runtime `File` variants. It was probably a mistake to include them anyway, but I didn't realize it at first. I'm inclined to skip deprecation and just expunge them outright in the next release. If a user really wanted this behavior, they could `readFile` themselves and use the `String`-based equivalent.
  4. [x] Deprecate the monadic argument query functions. They don't add much utility, and they were almost undocumented anyway.

None of these are particularly difficult to do. Unless there are objections, I can go ahead with these changes and release the refined API along with the new compile-time usage parser.

CC past contributors @Minoru @barrucadu @smaximov in case any of you have thoughts.

**Comment by Minoru** [comment]
Sorry for a "+1" comment, but I just wanted to second the idea of encouraging the usage of quasi-quoters and getting rid of `File` variants. QQ is what I ended up doing in my code, anyway, and it appears to me to be the only sane way to parse user's usage message and generate args parsers.

Thanks for the library.

**Comment by ryanartecona** [comment]
@Minoru Not at all! I'll take all the feedback I can get. If no one used this thing I wouldn't keep working on it :)

**Comment by ryanartecona** [comment]
All this stuff is done, and just released in [v0.7.0.0](https://hackage.haskell.org/package/docopt-0.7.0.0). I moved around a lot of stuff, but it's all much better documented now (with most things in haddocks instead of the readme). Cheers!
