### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by FranklinChen** [docopt/docopt.hs#11]
The documentation in `README.md` and `Docopt.hs` (and therefore the generated Haddock) still contain old API usage examples.

**Comment by ryanartecona** [comment]
I see a couple things I missed. Anything specifically you've spotted?

**Comment by FranklinChen** [comment]
I apologize for the vagueness. One sample code omission in `README.md` is that of missing `import System.Environment (getArgs)`.

Also `getArgOrExit` does not exist (this is in `README.md` and `Docopt.hs` Haddock comment block).

Finally, `Docopt.hs` uses `parseArgsOrExit` incorrectly.

**Comment by ryanartecona** [comment]
Thanks! Will get those corrected.

**Comment by ryanartecona** [comment]
[Bumped to 0.7.0.1](https://hackage.haskell.org/package/docopt-0.7.0.1) for those corrections. The docs should finish building soon; let me know if anything else is wrong!

**Comment by FranklinChen** [comment]
Thanks!
