### ISSUE TITLE
ARGUMENT equivalent to <argument>?

### ISSUE THREAD

**Issue by schoettl** [docopt/docopt.hs#12]
In the Python version, one can write `<argument>` and also `ARGUMENT` in the usage text.

How are upper-case words are handled in `Docopts.hs`? There is no hint in the [README.md](https://github.com/docopt/docopt.hs/blob/master/README.md); not in section [usage pattern](https://github.com/docopt/docopt.hs#argument) and not in section [differences from reference implementation](https://github.com/docopt/docopt.hs#differences-from-reference-python-implementation).

**Comment by ryanartecona** [comment]
You're right! Upcase arguments are indeed supported, just not mentioned anywhere. I've fixed that in 59f3af0.

**Comment by schoettl** [comment]
Nice, thanks :)
