### ISSUE TITLE
Stdin [-] doesn't parse correctly.

### ISSUE THREAD

**Issue by alexchandel** [docopt/docopt.hs#14]
When I have a usage of the form:
```
Usage:
  foo bar <baz>...
  foo bar [-]
```

I would expect EITHER `isPresent args (argument "baz")` OR `isPresent args (command "[-]")` (or `isPresent args (argument "[-]")` or however you're supposed to refer to it) to be true. Not both.

Yet `docopt.hs` consistently find `argument "baz"` even when none exists, if `[-]` is passed.

Also, the README and documentation are extremely vague on how the stdin argument `[-]` should be checked for.

**Comment by ryanartecona** [comment]
That `[-]` in the usage pattern is intended to be matched with `command "-"`. The square brackets mark it as an optional command, but aren't a part of the command name itself.

I think the `argument "baz"` issue is the same as in #15. The docs should also be clearer on how the `[-]` and `[--]` conventions are handled.

Thanks for submitting these issues! @alexchandel

**Comment by alexchandel** [comment]
@ryanartecona  np, docopt is my preferred arg parsing API, it'd be nice to use it in Haskell.
