### ISSUE TITLE
Repeated arguments are always marked present, even when absent

### ISSUE THREAD

**Issue by alexchandel** [docopt/docopt.hs#15]
Consider the following usage:
```
Usage:
  foo bar <baz>...
  foo --help

Options:
  -h, --help        Print this help message.
```

Even when called as `foo -h`, `isPresent args (argument "baz")` is always true. This is a serious bug, and it may affect #14.

**Comment by ryanartecona** [comment]
Oh no! You're right. It looks like there are some missing `False` cases in `isPresent` [here](https://github.com/docopt/docopt.hs/blob/master/System/Console/Docopt/Public.hs#L84-L89). Looks like there should also be a case for `MultiValue []` and `Counted 0`, to cover [the other constructors](https://github.com/docopt/docopt.hs/blob/master/System/Console/Docopt/Types.hs#L90-L95).

This will be an easy change to make. I should have some time this weekend to verify this is a fix and upload a new version.

**Comment by alexchandel** [comment]
@ryanartecona Any updates on this?

**Comment by ryanartecona** [comment]
@alexchandel Sorry, not yet. I didn't get around to this over the weekend. I don't really have an estimate for you, but it's on my todo list. :)
