### ISSUE TITLE
Should docopt print usage to stderr on failure?

### ISSUE THREAD

**Issue by Happy0** [docopt/docopt.hs#22]
Thanks for creating this very useful library! I've had fun and learned a lot by playing around with it.

I was thinking that it might more sense to print the usage to stderr rather than stdout. In situations where an application (which uses docopts) is used in a unix pipeline, the usage string is piped to the next application rather than being displayed to the user on stderr when invalid option flags, etc are used. If you agree with me, I'd be happy to submit a pull request which changes 'exitWithUsage' and similar functions to print on standard err instead.

Let me know what you think when you get the chance!

**Comment by ryanartecona** [comment]
@Happy0 That sounds appropriate! :+1:

**Comment by Happy0** [comment]
\o/ 

I'll submit a pull request soon :P

**Comment by ryanartecona** [comment]
Fixed by #23
