### ISSUE TITLE
Extra leading newline from the --help output

### ISSUE THREAD

**Issue by moll** [docopt/docopt.hs#28]
Hey,

I find formatting the quasiquoted usage string as follows to be aesthetically pleasing, but it seems to result in an extra leading newline when doing `--help`:

``` haskell
usage = [Docopt.docopt|
Usage: foo [options] <file>
|]
```

How about skipping that leading newline when reading it in?

Thanks!

**Comment by ryanartecona** [comment]
@moll Sorry for the long radio silence!

I agree, that is an annoying part of that quasiquoter. This is fixed in v0.7.0.5, which I just uploaded. Cheers!

**Comment by moll** [comment]
Yay. Thanks!
