### ISSUE TITLE
docopt.hs needs a new maintainer

### ISSUE THREAD

**Issue by ryanartecona** [docopt/docopt.hs#35]
I, @ryanartecona, initially wrote this library many years ago, but I have long since moved away from Haskell and am no longer actively maintaining this library.

If you are interested in taking over the maintainer role here, or know someone who is, please speak up!

**Comment by FullstackGJJ** [comment]
Since no one said anything, I am interested in figuring out how to fix #33 and take the reins over time.

**Comment by simonmichael** [comment]
Hi @FullstackGJJ, still interested in reviving this package ? The current hackage release needs a revision putting an upper bound on base, and a release supporting current GHCs is needed.

**Comment by FullstackGJJ** [comment]
@simonmichael yes, I would like to revive this package.

**Comment by simonmichael** [comment]
Great! How soon do you think you could upload a quick bugfix release updating it for current ghc (#34) ? :-) You'd need hackage upload permission from @ryanartecona .

**Comment by ryanartecona** [comment]
@FullstackGJJ Sorry for not responding earlier. Can you give me your hackage.haskell.org username, so I can add you to the maintainer group there?

**Comment by FullstackGJJ** [comment]
Yes, it is "fullstackgjj"

**Comment by FullstackGJJ** [comment]
@simonmichael I anticipate within the day of having hackage upload permission :)

**Comment by ryanartecona** [comment]
@FullstackGJJ Ok thanks, I've added you as a maintainer to both the package on hackage and this repo in GitHub. You should have all the permissions you need to make new releases.

**Comment by FullstackGJJ** [comment]
Awesome, thank you. I accepted the pull request and will be creating a release.

**Comment by simonmichael** [comment]
Hi @FullstackGJJ! You closed this, but the latest Hackage release is still 0.7.0.5, Uploaded | by ryanartecona at 2016-11-10T15:59:14Z.

**Comment by simonmichael** [comment]
(Related: #43.)

**Comment by FullstackGJJ** [comment]
@simonmichael I closed this because the task of finding a new maintainer was done. I will be addressing #43.
