### ISSUE TITLE
Failing to build on nix due to 0.7.0.6 not being on hackage

### ISSUE THREAD

**Issue by Xitian9** [docopt/docopt.hs#43]
0.7.0.6 is on hackage as a candidate release, but not yet a proper release. Since 0.7.0.5 fails to build, it is now marked as ‘broken’ on nix and anything which depends on it will not compile.

**Comment by FullstackGJJ** [comment]
Unfortunately I didn't identify issues with 0.7.0.6 package candidate before publishing it. I intend to move onto 0.7.0.7 which should fix all of your issues. The package candidate is here (https://hackage.haskell.org/package/docopt-0.7.0.7/candidate) it would be a huge plus if you can verify that referencing this package candidate fixes your problems. I will be testing the same.

**Comment by Xitian9** [comment]
Thanks! I can confirm that if I use the current master branch within nix (i.e. bdc4c679bf0185ab6c1895172f011193d9e9922c, which I believe is your release candidate), then things build properly.

**Comment by FullstackGJJ** [comment]
Awesome, I tested out 0.7.0.7 package candidate as well and works as expected for me as well. Will publish the package candidate officially tomorrow.

**Comment by FullstackGJJ** [comment]
Package has been published https://hackage.haskell.org/package/docopt
