### ISSUE TITLE
Maintainership tranferral

### ISSUE THREAD

**Issue by martijnbastiaan** [docopt/docopt.hs#55]
I've already spoken to @ryanartecona through e-mail, he said he'd be happy to transfer maintainership. In order to do so (and if @FullstackGJJ is fine with it too), we'd need to do two things:

- [x] Add maintainers with sufficient rights to `docopt/docopt.hs`
  - I'm hoping we can add both myself (@martijnbastiaan) and my colleague (@DigitalBrains1)
- [x] Add maintainers with sufficient rights to Hackage
  - Just a comment on this thread will suffice for Hackage admins to transfer maintainership

Thank you!

**Comment by ryanartecona** [comment]
:+1: confirmed and approved!

**Comment by ryanartecona** [comment]
Turns out I do still have access to my hackage account, so I've added you @martijnbastiaan to maintainers there. I've also added both of you to this repo, @martijnbastiaan as admin and @DigitalBrains1 as maintainer. Thanks for taking over!
